### ISSUE TITLE
import问题求助

### ISSUE THREAD

**Issue by weiran102** [leaguecn/readFls#1]
您好，请问您知道为什么我安装完.exe文件和注册完faro之后依然无法import .dll文件吗
![image](https://github.com/leaguecn/readFls/assets/149149690/a745d17e-6338-4ee8-8a59-8500cd4373db)

**Comment by leaguecn** [comment]
请确保安装的是本仓库的SDK版本，且以下两个路径中的文件存在：
+ C:\Windows\WinSxS\amd64_faro.ls_1d23f5635ba800ab_1.1.905.1_none_36a3d9b167a7571f\iQOpen.dll
+ C:\Windows\WinSxS\amd64_faro.ls_1d23f5635ba800ab_1.1.905.1_none_36a3d9b167a7571f\FARO.LS.SDK.dll
如果上述两个文件不存在所引用的路径，必然无法import。

**Comment by weiran102** [comment]
非常感谢您的回复，我确实是安装的该版本的sdk，并且在路径中存在这两个文件，但是我这里一直显示无法打开源文件，并且路径指向D:\Mycode\vscode2\fls2las\fls2las\x64\Debug，而且不知道为什么显示的是无法打开iQOpen.tlh，而不是dll文件，困惑已久，不知道您有没有解决这种问题的思路，万分感谢！！！！！！
![image](https://github.com/leaguecn/readFls/assets/149149690/aa619c25-18f9-4534-b2ac-5378a0c5f191)

**Comment by leaguecn** [comment]
文中所列主要代码主要是参考[FARO SDK 2018指导文档](https://downloads.faro.com/index.php/s/Cj3qyyqAEW2CzAG?dir=undefined&openfile=36692)整理，请确保你所使用的vs(visual studio) 版本不要太新（当然可能不是这个原因）。
+ dll是动态链接库，在编译的时候不需要，只在程序运行时调用，代码编译一般是调用头文件（*.h/*.hpp）+ 库文件（*.lib）；
+ 查阅[巨硬的import文档](https://learn.microsoft.com/zh-cn/cpp/preprocessor/hash-import-directive-cpp?view=msvc-170)确实是提到了ltb, lib等的导入，未提及lth;
+ 如你截图所示，错误太多，先把其他明显错误（540个错误）解决了，再来推敲程序的主要异常所在，不要一开始就一口咬定是import问题；
+ 遇事先自己在网上找答案，提高自身的解决问题能力，一般的问题在网上的博客都会有答案；
+ 网上有篇[博客](https://blog.csdn.net/weixin_43160744/article/details/118437263)和你的问题有有点相似，祝你好运！

**Comment by weiran102** [comment]
非常感谢您的帮助！！！！！！！！！！！！
